version: "3.6"
services:
  postgres:
    image: "postgres:10.5-alpine"
    ports:
      - "5432:5432"
    volumes:
      - "postgres:/var/lib/postgresql/data"
  seq:
    image: "datalust/seq"
    ports:
      - "5341:80"
    volumes:
      - "seq:/data"
    environment:
      - ACCEPT_EULA=Y
volumes:
  postgres:
  seq: