version: "3.6"
services:
  postgres:
    image: "postgres:10.5-alpine"
    ports:
      - "5432:5432"
    volumes:
      - "triple_triad_postgres:/var/lib/postgresql/data"
volumes:
  triple_triad_postgres: